#!/bin/bash
clear

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
BLUE="\033[4;34m"
BG_BLU="\033[44;1m" # BG BIRU
Xark='\e[0m'
GREN="\033[0;32m"
clear
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}

# Function to display menu
display_menu() {
baris_panjang
echo -e "\e[95m          NOOBVPNS \e[0m"
baris_panjang
baris_panjang
    echo "1. Install NoobzVpn-Server"
    echo "2. Add User"
    echo "3. Block User"
    echo "4. Unblock User"
    echo "5. Set Expiration"
    echo "6. Renew Expiration"
    echo "7. Change Password"
    echo "8. Rename User"
    echo "9. Remove User"
    echo "10. Remove All Users"
    echo "11. Info User noobs"
    echo "12. Info all user noobs"
	echo "13. Check Status"
	echo "14. Check Logs"
	echo "15. Restart NoobzVpn"
    echo "16. Exit"
	echo "00. Uninstall Noobzvpn-Server"
baris_panjang
}

# Function to install NoobzVpn-Server
install_noobzvpn_server() {
    read -p "Are you sure you want to install noobzvpn service? (yes/no): " confirm
    if [ "$confirm" == "yes" ]; then
    echo "Starting NoobzVpn-Server installation..."
    # Your installation commands go here
	apt update && apt install git && git clone https://github.com/NiLphreakz/noobzvpns.git && cd noobzvpns/ && sh ./install.sh && systemctl start noobzvpns.service && systemctl status noobzvpns.service -l
    echo "NoobzVpn-Server installed successfully."
	 else
        echo "Operation cancelled."
    fi
}

# Function to add a new user
add_user() {
clear
baris_panjang
echo -e "\e[95m         CREATE TITLE NOOB \e[0m"
baris_panjang
echo
    read -p " Username   : " username
    read -p " Password   : " password
    read -p " Expiry in  : " days
    noobzvpns --add-user "$username" "$password"
    noobzvpns --expired-user "$username" "$days"
clear
baris_panjang
echo -e "\e[97;1m NOOBVPNS SERVER \e[0m"
echo
echo -e "\e[93;1m Username \e[0m   : $username "
echo -e "\e[93;1m Password \e[0m   : $password "
echo -e "\e[93;1m Expiry in\e[0m   : $days "
echo -e "\e[93;1m Domain   \e[0m   : $(cat /etc/xray/domain) "
echo -e "\e[92;1m Port WS  \e[0m   : 8080 "
echo -e "\e[92;1m Port Tls \e[0m   : 8443"
echo
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to block a user
block_user() {
clear
baris_panjang
echo -e "\e[95m        LOCKED ACCOUNT \e[0m"
baris_panjang
    read -p "Enter username to block: " username
    noobzvpns --block-user "$username"
sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to unblock a user
unblock_user() {
clear
baris_panjang
echo -e "\e[95m       UNLOCK ACCOUNT \e[0m"
baris_panjang
    read -p "Enter username to unblock: " username
    noobzvpns --unblock-user "$username"
sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to set expiration for a user
set_expiration() {
clear
baris_panjang
echo -e "\e[95;1m         SET EXPIRY IN \e[0m"
baris_panjang
echo
    read -p " Username   : " username
    read -p " Expired in : " days
    noobzvpns --expired-user "$username" "$days"
sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
echo -e "\e[92;1m EXPIRY   : \e[93;1m $days \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to renew expiration for a user
renew_expiration() {
clear
    read -p "Enter username to renew expiration: " username
    noobzvpns --renew-user "$username"
sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to change password for a user
change_password() {
clear
baris_panjang
echo -e "\e[95m        CHANGE PASSWORD \e[0m"
baris_panjang
echo
    read -p "Enter username: " username
    read -p "Enter new password: " new_password
    noobzvpns --password-user "$username" "$new_password"
sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
echo -e "\e[92;1m NEW PW   : \e[93;1m $new_password\e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to rename a user
rename_user() {
clear
baris_panjang
echo -e "\e[95m        RENAME USER   \e[0m"
baris_panjang
echo
    read -p "Enter current username: " old_username
    read -p "Enter new username: " new_username
    noobzvpns --rename-user "$old_username" "$new_username"
    sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m OLD USERNAME : \e[93;1m $old_username \e[0m"
echo -e "\e[92;1m NEW USERNAME : \e[93;1m $new_username \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to remove a user
remove_user() {
clear
baris_panjang
echo -e "\e[95m        REMOVED NOOBS \e[0m"
baris_panjang
echo
    read -p "Enter username to remove: " username
    noobzvpns --remove-user "$username"
    sleep 2
    clear
baris_panjang
echo -e "\e[5;32m Successfully \e[0m"
echo
echo -e "\e[92;1m USERNAME : \e[93;1m $username \e[0m"
baris_panjang
echo
read -p "Back To Menu"
menu
}

# Function to remove all users
remove_all_users() {
    read -p "Are you sure you want to remove all users? (yes/no): " confirm
    if [ "$confirm" == "yes" ]; then
        noobzvpns --remove-all-user
    else
        echo "Operation cancelled."
    fi
}

# Function to get info for a user
info_user() {
    read -p "Enter username: " username
    noobzvpns --info-user "$username"
}

# Function to get info for all users
info_all_users() {
    noobzvpns --info-all-user
}

# Function to check status
check_status() {
    systemctl status noobzvpns.service -l
}

# Function to check logs
check_logs() {
    journalctl -u noobzvpns.service
}

# Function to restart noobzvpn
restart_noobzvpn() {
    systemctl restart noobzvpns.service
}

# Function to uninstall noobzvpn server
uninstall_noobzvpn() {
    read -p "Are you sure you want to uninstall noobzvpn service? (yes/no): " confirm
    if [ "$confirm" == "yes" ]; then
    cd noobzvpns/ && sh ./uninstall.sh && cd && rm -r noobzvpns
	 else
        echo "Operation cancelled."
    fi
}

# Main script
while true; do
    display_menu
    read -p "Enter your choice: " choice
    case $choice in
        1) install_noobzvpn_server ;;
        2) add_user ;;
        3) block_user ;;
        4) unblock_user ;;
        5) set_expiration ;;
        6) renew_expiration ;;
        7) change_password ;;
        8) rename_user ;;
        9) remove_user ;;
        10) remove_all_users ;;
        11) info_user ;;
        12) info_all_users ;;
		13) check_status ;;
		14) check_logs ;;
		15) restart_noobzvpn ;;
        16) exit ;;
		00) uninstall_noobzvpn ;;
        *) echo "Invalid choice. Please enter a number between 1 and 13." ;;
    esac
done
